<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="segwayrmp400">

<!-- Some Color Materials -->
  <material name="Green"><color rgba="0.0 0.8 0.0 1.0"/></material>
  <material name="Red"><color rgba="0.8 0.0 0.0 1.0"/></material>
  <material name="White"><color rgba="1.0 1.0 1.0 1.0"/></material>
  <material name="Blue"><color rgba="0.0 0.0 0.8 1.0"/></material>
  <material name="Black"><color rgba="0.0 0.0 0.0 1.0"/></material>
  <material name="Grey"><color rgba="0.3 0.3 0.3 1.0"/></material>
  <material name="atrv_orange"><color rgba="0.8 0.16 0.0 1" /></material>
  <material name="clear"><color rgba="0 0 0 0"/></material>

<!-- xacro parameters -->
  <xacro:property name="M_PI" value="3.14159"/>
  <!-- Robot parameters -->
  <xacro:property name="ground_clearance" value="0.13" />
  <!-- This is not including the bumpers -->
  <xacro:property name="chassis_length" value="0.83" />
  <!-- This is including the bumpers -->
  <xacro:property name="chassis_length_bumpers" value="1.02" />
  <!-- This is not including the wheels -->
  <xacro:property name="chassis_width" value="0.46" />
  <!-- This is not including equipment and racks on the top -->
  <xacro:property name="chassis_height" value="0.50" />
  <xacro:property name="wheel_radius" value="0.20"/>
  <xacro:property name="wheel_width" value="0.15"/>

<!-- xacro macros -->
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0" />
      </inertial>
  </xacro:macro>

<!-- links -->

  <!-- base_link -->
  <!-- The link that is the origin of all of the components of the -->
  <!-- robot and should also represent the main chassis via inertial, -->
  <!-- visual, and geometry elements of the link -->
  <link name="base_link">
    <xacro:default_inertial mass="80"/>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://segwayrmp400_description/meshes/segwayrmp400_chassis.stl"/>
      </geometry>
      <material name="Grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${chassis_height/2.0}" rpy="0 0 0" />
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
    </collision>
  </link>

  <!-- hitch Link -->
  <link name="hitch_link"/>

  <joint name="base_hitch_joint" type="fixed">
    <origin xyz="-0.56 0.0 0.0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="hitch_link"/>
  </joint>

  <!-- laser Link -->
  <link name="base_laser_link"/>

  <joint name="base_laser_joint" type="fixed">
    <origin xyz="0.55 0.0 0.25" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_laser_link"/>
  </joint>

  <!-- This is a macro for the links that describe the wheels -->
  <xacro:macro name="wheel" params="prefix reflect_x reflect_y">
    <link name="${prefix}_wheel_link">
      <xacro:default_inertial mass="1"/>

      <visual>
        <origin xyz="0 0 ${wheel_width/2}" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://segwayrmp400_description/meshes/segwayrmp400_wheel.stl"/>
        </geometry>
        <material name="Grey"/>
      </visual>

      <collision>
        <origin xyz="0 0 ${wheel_width/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <!-- base_link -> ${prefix}_wheel_link -->
    <joint name="${prefix}_wheel_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${(0.27)*reflect_x} ${(chassis_width/2 + 0.03)*reflect_y} ${0.1}"
              rpy="${(M_PI/2)*reflect_y*-1} 0 0"/>
    </joint>
  </xacro:macro>

  <!-- left_front_wheel_link -->
  <xacro:wheel prefix="left_front" reflect_x="1" reflect_y="1" />
  <!-- left_rear_wheel_link -->
  <xacro:wheel prefix="left_rear" reflect_x="-1" reflect_y="1" />
  <!-- right_front_wheel_link -->
  <xacro:wheel prefix="right_front" reflect_x="1" reflect_y="-1" />
  <!-- right_rear_wheel_link -->
  <xacro:wheel prefix="right_rear" reflect_x="-1" reflect_y="-1" />

</robot>